apiVersion: serving.knative.dev/v1
kind: Service
metadata:
  name: integration-gateway
  namespace: api-for-warp-drive
  labels:
    cloud.googleapis.com/location: us-west1
spec:
  template:
    metadata:
      annotations:
        autoscaling.knative.dev/maxScale: "10"
        autoscaling.knative.dev/minScale: "1"
        run.googleapis.com/startup-cpu-boost: "true"
        run.googleapis.com/cpu-throttling: "false"
        run.googleapis.com/cloudsql-instances: ""
        run.googleapis.com/execution-environment: "gen2"
        run.googleapis.com/vpc-access-connector: ""
        run.googleapis.com/vpc-access-egress: "private-ranges-only"
    spec:
      containerConcurrency: 80
      timeoutSeconds: 300
      serviceAccountName: drlucyautomation@api-for-warp-drive.iam.gserviceaccount.com
      containers:
      - image: us-west1-docker.pkg.dev/api-for-warp-drive/cloud-run-source-deploy/integration-gateway
        ports:
        - name: http1
          containerPort: 8080
        resources:
          limits:
            cpu: "2"
            memory: 2Gi
        env:
        - name: NODE_ENV
          value: "production"
        - name: API_KEY
          valueFrom:
            secretKeyRef:
              key: latest
              name: API_KEY
        - name: DB_PASSWORD
          valueFrom:
            secretKeyRef:
              key: latest
              name: DB_PASSWORD
        - name: INTEGRATION_TOKEN
          valueFrom:
            secretKeyRef:
              key: latest
              name: INTEGRATION_TOKEN
        securityContext:
          runAsNonRoot: true
          allowPrivilegeEscalation: false
          capabilities:
            drop:
            - ALL
          seccompProfile:
            type: RuntimeDefault

