name: Deploy Webhook Service

on:
  push:
    branches:
      - main
    paths:
      - 'webhooks/**'
      - '.github/workflows/webhook-deploy.yml'

jobs:
  deploy:
    name: Build and Deploy
    runs-on: ubuntu-latest
    
    env:
      PROJECT_ID: api-for-warp-drive
      GKE_CLUSTER: lucy-cluster
      GKE_ZONE: us-central1
      IMAGE: gcr.io/${{ github.event.repository.owner.name }}/lucy-webhook

    steps:
    - name: Checkout
      uses: actions/checkout@v2

    - name: Setup Google Cloud CLI
      uses: google-github-actions/setup-gcloud@v0.2.0
      with:
        service_account_key: ${{ secrets.DRLUCYATUOMATION_KEY }}
        project_id: ${{ env.PROJECT_ID }}

    - name: Configure Docker
      run: |
        gcloud auth configure-docker
        
    - name: Get GKE Credentials
      uses: google-github-actions/get-gke-credentials@v0.2.1
      with:
        cluster_name: ${{ env.GKE_CLUSTER }}
        location: ${{ env.GKE_ZONE }}
        credentials: ${{ secrets.DRLUCYATUOMATION_KEY }}

    - name: Build
      run: |
        docker build -t $IMAGE:$GITHUB_SHA \
          --build-arg GITHUB_SHA="$GITHUB_SHA" \
          --build-arg GITHUB_REF="$GITHUB_REF" \
          webhooks/

    - name: Push
      run: |
        docker push $IMAGE:$GITHUB_SHA
        docker tag $IMAGE:$GITHUB_SHA $IMAGE:latest
        docker push $IMAGE:latest

    - name: Deploy
      run: |
        kubectl apply -f webhooks/deployment/
        kubectl set image deployment/lucy-webhook \
          webhook-service=$IMAGE:$GITHUB_SHA
        kubectl rollout status deployment/lucy-webhook
