name: Dr. Memoria Firebase Functions CI/CD

on:
  push:
    branches: 
      - main
      - develop
    paths:
      - 'functions/**'
  pull_request:
    branches:
      - main
      - develop
    paths:
      - 'functions/**'

env:
  NODE_VERSION: 16.x

jobs:
  test-and-lint:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    
    - name: Use Node.js ${{ env.NODE_VERSION }}
      uses: actions/setup-node@v3
      with:
        node-version: ${{ env.NODE_VERSION }}
        cache: 'npm'
        cache-dependency-path: functions/package-lock.json
    
    - name: Install Dependencies
      working-directory: ./functions
      run: npm ci
    
    - name: Run Linter
      working-directory: ./functions
      run: npm run lint
    
    - name: Run Unit Tests
      working-directory: ./functions
      run: npm test
    
    - name: Run Coverage
      working-directory: ./functions
      run: npm run coverage

  deploy-staging:
    needs: test-and-lint
    if: github.ref == 'refs/heads/develop'
    runs-on: ubuntu-latest
    environment: staging
    
    steps:
    - uses: actions/checkout@v3
    
    - name: Use Node.js ${{ env.NODE_VERSION }}
      uses: actions/setup-node@v3
      with:
        node-version: ${{ env.NODE_VERSION }}
    
    - name: Install Firebase CLI
      run: npm install -g firebase-tools
    
    - name: Deploy to Staging Firebase
      working-directory: ./functions
      run: |
        firebase use staging
        firebase deploy --only functions
      env:
        FIREBASE_TOKEN: ${{ secrets.FIREBASE_STAGING_TOKEN }}
        FIREBASE_API_KEY: ${{ secrets.FIREBASE_STAGING_API_KEY }}
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

  deploy-production:
    needs: test-and-lint
    if: github.ref == 'refs/heads/main'
    runs-on: ubuntu-latest
    environment: production
    
    steps:
    - uses: actions/checkout@v3
    
    - name: Use Node.js ${{ env.NODE_VERSION }}
      uses: actions/setup-node@v3
      with:
        node-version: ${{ env.NODE_VERSION }}
    
    - name: Install Firebase CLI
      run: npm install -g firebase-tools
    
    - name: Deploy to Production Firebase
      working-directory: ./functions
      run: |
        firebase use production
        firebase deploy --only functions
      env:
        FIREBASE_TOKEN: ${{ secrets.FIREBASE_PRODUCTION_TOKEN }}
        FIREBASE_API_KEY: ${{ secrets.FIREBASE_PRODUCTION_API_KEY }}
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

  notify:
    needs: [test-and-lint, deploy-staging, deploy-production]
    if: always()
    runs-on: ubuntu-latest
    
    steps:
    - name: Send Slack Notification
      uses: 8398a7/action-slack@v3
      with:
        status: ${{ job.status }}
        fields: repo,message,commit,author,action,eventName,ref,workflow
      env:
        SLACK_WEBHOOK_URL: ${{ secrets.SLACK_WEBHOOK }}
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
