apiVersion: serving.knative.dev/v1
kind: Service
metadata:
  name: mock-sallyport-service
  namespace: default
  labels:
    cloud.googleapis.com/location: us-west1
  annotations:
    run.googleapis.com/ingress: all
    run.googleapis.com/ingress-status: all
spec:
  template:
    metadata:
      annotations:
        autoscaling.knative.dev/maxScale: "10"
        autoscaling.knative.dev/minScale: "1"
        run.googleapis.com/cpu-throttling: "false"
        run.googleapis.com/execution-environment: gen2
        run.googleapis.com/memory: "1Gi"
    spec:
      containerConcurrency: 80
      containers:
      - image: gcr.io/api-for-warp-drive/mock-sallyport-service:latest
        name: mock-sallyport-service
        ports:
        - containerPort: 8080
          name: http1
        env:
        - name: PORT
          value: "8080"
        - name: JWT_SECRET
          valueFrom:
            secretKeyRef:
              name: sallyport-jwt-secret
              key: secret
        - name: ENVIRONMENT
          value: "development"
        - name: GCP_PROJECT
          value: "api-for-warp-drive"
        resources:
          limits:
            cpu: "1000m"
            memory: "1Gi"
          requests:
            cpu: "100m"
            memory: "256Mi"
        startupProbe:
          httpGet:
            path: /health
            port: 8080
          initialDelaySeconds: 5
          periodSeconds: 10
          timeoutSeconds: 5
          failureThreshold: 3
        livenessProbe:
          httpGet:
            path: /health
            port: 8080
          initialDelaySeconds: 30
          periodSeconds: 60
          timeoutSeconds: 5
          failureThreshold: 3
        readinessProbe:
          httpGet:
            path: /status
            port: 8080
          initialDelaySeconds: 5
          periodSeconds: 10
          timeoutSeconds: 5
          failureThreshold: 3
      serviceAccountName: integration-gateway-service-account
  traffic:
  - percent: 100
    latestRevision: true
