# Cloud Build CI/CD Pipeline Configuration for AIXTIV Symphony Project
# This configuration enables frequent deployments (every 10 minutes)

steps:
  # Build and push TTS service container
  - name: 'gcr.io/cloud-builders/docker'
    id: 'build-tts'
    args: ['build', '-t', 'us-west1-docker.pkg.dev/api-for-warp-drive/aixtiv-symphony/tts:$COMMIT_SHA', './backend/services/tts']
  - name: 'gcr.io/cloud-builders/docker'
    id: 'push-tts'
    args: ['push', 'us-west1-docker.pkg.dev/api-for-warp-drive/aixtiv-symphony/tts:$COMMIT_SHA']
    waitFor: ['build-tts']
  
  # Build and push Sentiment service container
  - name: 'gcr.io/cloud-builders/docker'
    id: 'build-sentiment'
    args: ['build', '-t', 'us-west1-docker.pkg.dev/api-for-warp-drive/aixtiv-symphony/sentiment:$COMMIT_SHA', './backend/services/sentiment']
  - name: 'gcr.io/cloud-builders/docker'
    id: 'push-sentiment'
    args: ['push', 'us-west1-docker.pkg.dev/api-for-warp-drive/aixtiv-symphony/sentiment:$COMMIT_SHA']
    waitFor: ['build-sentiment']
  
  # Build and push API service container
  - name: 'gcr.io/cloud-builders/docker'
    id: 'build-api'
    args: ['build', '-t', 'us-west1-docker.pkg.dev/api-for-warp-drive/aixtiv-symphony/api:$COMMIT_SHA', './backend/api']
  - name: 'gcr.io/cloud-builders/docker'
    id: 'push-api'
    args: ['push', 'us-west1-docker.pkg.dev/api-for-warp-drive/aixtiv-symphony/api:$COMMIT_SHA']
    waitFor: ['build-api']
  
  # Create a tagged version with 'latest' for quick reference
  - name: 'gcr.io/cloud-builders/docker'
    id: 'tag-tts-latest'
    args: ['tag', 
           'us-west1-docker.pkg.dev/api-for-warp-drive/aixtiv-symphony/tts:$COMMIT_SHA', 
           'us-west1-docker.pkg.dev/api-for-warp-drive/aixtiv-symphony/tts:latest']
    waitFor: ['push-tts']
  - name: 'gcr.io/cloud-builders/docker'
    id: 'push-tts-latest'
    args: ['push', 'us-west1-docker.pkg.dev/api-for-warp-drive/aixtiv-symphony/tts:latest']
    waitFor: ['tag-tts-latest']
  
  - name: 'gcr.io/cloud-builders/docker'
    id: 'tag-sentiment-latest'
    args: ['tag', 
           'us-west1-docker.pkg.dev/api-for-warp-drive/aixtiv-symphony/sentiment:$COMMIT_SHA', 
           'us-west1-docker.pkg.dev/api-for-warp-drive/aixtiv-symphony/sentiment:latest']
    waitFor: ['push-sentiment']
  - name: 'gcr.io/cloud-builders/docker'
    id: 'push-sentiment-latest'
    args: ['push', 'us-west1-docker.pkg.dev/api-for-warp-drive/aixtiv-symphony/sentiment:latest']
    waitFor: ['tag-sentiment-latest']
  
  - name: 'gcr.io/cloud-builders/docker'
    id: 'tag-api-latest'
    args: ['tag', 
           'us-west1-docker.pkg.dev/api-for-warp-drive/aixtiv-symphony/api:$COMMIT_SHA', 
           'us-west1-docker.pkg.dev/api-for-warp-drive/aixtiv-symphony/api:latest']
    waitFor: ['push-api']
  - name: 'gcr.io/cloud-builders/docker'
    id: 'push-api-latest'
    args: ['push', 'us-west1-docker.pkg.dev/api-for-warp-drive/aixtiv-symphony/api:latest']
    waitFor: ['tag-api-latest']
  
  # Update Kubernetes deployments with new images
  - name: 'gcr.io/cloud-builders/kubectl'
    id: 'deploy-tts'
    args:
      - 'set'
      - 'image'
      - 'deployment/tts-service'
      - 'tts-service=us-west1-docker.pkg.dev/api-for-warp-drive/aixtiv-symphony/tts:$COMMIT_SHA'
    env:
      - 'CLOUDSDK_COMPUTE_ZONE=us-west1-a'
      - 'CLOUDSDK_CONTAINER_CLUSTER=aixtiv-cluster-production'
      - 'CLOUDSDK_CORE_PROJECT=api-for-warp-drive'
    waitFor: ['push-tts']
  
  - name: 'gcr.io/cloud-builders/kubectl'
    id: 'deploy-sentiment'
    args:
      - 'set'
      - 'image'
      - 'deployment/sentiment-service'
      - 'sentiment-service=us-west1-docker.pkg.dev/api-for-warp-drive/aixtiv-symphony/sentiment:$COMMIT_SHA'
    env:
      - 'CLOUDSDK_COMPUTE_ZONE=us-west1-a'
      - 'CLOUDSDK_CONTAINER_CLUSTER=aixtiv-cluster-production'
      - 'CLOUDSDK_CORE_PROJECT=api-for-warp-drive'
    waitFor: ['push-sentiment']
  
  - name: 'gcr.io/cloud-builders/kubectl'
    id: 'deploy-api'
    args:
      - 'set'
      - 'image'
      - 'deployment/symphony-api'
      - 'symphony-api=us-west1-docker.pkg.dev/api-for-warp-drive/aixtiv-symphony/api:$COMMIT_SHA'
    env:
      - 'CLOUDSDK_COMPUTE_ZONE=us-west1-a'
      - 'CLOUDSDK_CONTAINER_CLUSTER=aixtiv-cluster-production'
      - 'CLOUDSDK_CORE_PROJECT=api-for-warp-drive'
    waitFor: ['push-api']
  
  # Check deployment status
  - name: 'gcr.io/cloud-builders/kubectl'
    id: 'check-deployments'
    args:
      - 'rollout'
      - 'status'
      - 'deployment/symphony-api'
    env:
      - 'CLOUDSDK_COMPUTE_ZONE=us-west1-a'
      - 'CLOUDSDK_CONTAINER_CLUSTER=aixtiv-cluster-production'
      - 'CLOUDSDK_CORE_PROJECT=api-for-warp-drive'
    waitFor: ['deploy-tts', 'deploy-sentiment', 'deploy-api']

# Define artifacts to be stored after the build
artifacts:
  objects:
    location: 'gs://api-for-warp-drive-builds/$PROJECT_ID/$COMMIT_SHA/'
    paths: ['cloudbuild-logs.txt']

# Set a shorter build timeout for frequent deployments (10 minutes)
timeout: '600s'

# Define substitution variables 
substitutions:
  _CLUSTER_NAME: 'aixtiv-cluster-production'
  _CLUSTER_ZONE: 'us-west1-a'

# Add tags for better organization in the Cloud Build console
tags: ['aixtiv-symphony', 'deployment', 'production']

