name: Domain Ownership Verification

on:
  workflow_dispatch:
    inputs:
      domain:
        description: 'Domain to verify (e.g., vision.coaching2100.com)'
        required: true
        type: string
      method:
        description: 'Verification method'
        required: true
        default: 'dns'
        type: choice
        options:
          - dns
          - file
          - meta

jobs:
  verify-ownership:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '20'
          cache: 'npm'

      - name: Install dependencies
        run: npm ci

      - name: Check domain status
        run: node scripts/domain-all-in-one-cli.js check-domain
        env:
          DOMAIN: ${{ inputs.domain }}
          FIREBASE_PROJECT_ID: ${{ secrets.FIREBASE_PROJECT_ID }}
          FIREBASE_SERVICE_ACCOUNT_KEY: ${{ secrets.FIREBASE_SERVICE_ACCOUNT_KEY }}

      - name: Generate verification token
        run: node scripts/domain-all-in-one-cli.js generate-token
        env:
          DOMAIN: ${{ inputs.domain }}
          VERIFICATION_METHOD: ${{ inputs.method }}

      - name: Apply verification
        run: node scripts/domain-all-in-one-cli.js verify-ownership
        env:
          DOMAIN: ${{ inputs.domain }}
          VERIFICATION_METHOD: ${{ inputs.method }}
          GODADDY_API_KEY: ${{ secrets.GODADDY_API_KEY }}
          GODADDY_API_SECRET: ${{ secrets.GODADDY_API_SECRET }}

      - name: Validate verification
        run: node scripts/domain-all-in-one-cli.js validate-verification
        env:
          DOMAIN: ${{ inputs.domain }}
          VERIFICATION_METHOD: ${{ inputs.method }}

      - name: Update domain status
        if: success()
        run: node scripts/domain-all-in-one-cli.js update-status verified
        env:
          DOMAIN: ${{ inputs.domain }}

