
# cloudbuild.yaml

steps:
  # Step 1: Install dependencies
  - name: 'gcr.io/cloud-builders/npm'
    args: ['install']
    dir: 'functions'

  # Step 2: Run tests (optional)
  - name: 'gcr.io/cloud-builders/npm'
    args: ['run', 'test']
    dir: 'functions'

  # Step 3: Deploy Firebase Function to specified region
  - name: 'gcr.io/google.com/cloudsdktool/cloud-sdk'
    entrypoint: 'bash'
    args:
      - '-c'
      - |
        gcloud functions deploy agentPulsePanel         --runtime nodejs20         --trigger-http         --allow-unauthenticated         --region=us-west1         --source=functions         --entry-point=agentPulseHandler

  # Step 4: Notify deployment to Firestore or logging service
  - name: 'gcr.io/google.com/cloudsdktool/cloud-sdk'
    entrypoint: 'bash'
    args:
      - '-c'
      - |
        echo "Deployment complete for agentPulsePanel" | gcloud logging write agent-deployments

timeout: 900s

tags:
  - aixtiv
  - visionlake
  - agent-deploy
