name: ASOOS API CI Tests

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  run-postman-tests:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v3

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 18

      - name: Install Newman
        run: npm install -g newman

      - name: Run Newman Tests
        run: newman run ASOOS_API_MasterCollection.json -e ASOOS_API_Environment.json --reporters cli,json --reporter-json-export newman-report.json

